### ISSUE TITLE
Move toward a monorepo

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#146]
- [x] Update README.md (including individual package readmes)
- [x] Make sure license and notice are published with npm package (#178)
- [x] Move PRs from js-core to js-base (@vigneshshanmugam - Do it after checking other items) 
- [x] introduce Contributing.md with release section elastic/apm-agent-js-base#147    
- [x] Fix Opbeans-frontend (https://github.com/elastic/opbeans-frontend/pull/6)
- [x] Add deprecation notice to js-core (Should only do it after we have published a version with monorepo) (https://github.com/elastic/apm-agent-js-core/pull/41)
- [x] Fix release script
- [x] Fix publishing script after doing change-log generation elastic/apm-agent-js-base#164    
- [x] Split travis build matrix for packages and use appropriate saucelabs account (@jahtalab)
- [x] Add eslint rule object short hand (#165)
- [x] Adopt changelog commit message convention that includes the package name, e.g. `feat(core)` (#164)
- [x] Run each package test in separate travis VM to increase concurrency  (@jahtalab)
- [x] Lerna run test in verbose
- [x] Fix lint script
- [x] Create the package structure
- [x] Move js-core to the git repo
- [x] Move js-base to its package
- [x] Hoist common dev dependencies to the top level
- [x] Fix apm-integration-testing (it clones the github repo) (@jahtalab )

Considering:
- https://github.com/lerna/lerna
- https://yarnpkg.com/lang/en/docs/workspaces/
