### ISSUE TITLE
Improve build configuration for release and testing

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#308]
Our build setup has lots of code repetition for both releasing and testing parts and have to be refactored to make the processing easier. Any small change in single config have to be reflected everywhere on the repo - this makes the development a bit harder. 

+ [ ] Move to rollup for releasing the library elastic/apm-agent-rum-js#313 
+ [x] Unify babel configuration for releasing UMD/CommonJS version elastic/apm-agent-rum-js#355 
+ [ ] Move testing setup to Rollup if required or stay with Webpack
+ [x] Ability to watch for files on development and run individual tests elastic/apm-agent-rum-js#358 

I have put the tasks in the order of priority to make it easier for anyone to pick it up.

**Comment by vigneshshanmugam** [comment]
Initial test of Rollup for releasing the library has yielded bundle size reduction of `0.4kB` minified and gzipped

```
PASS  ./dist/bundles/elastic-apm-rum.umd.min.js: 15.72KB < maxSize 16KB (gzip)
PASS  ./dist/rollup/elastic-apm-rum.umd.min.js: 15.31KB < maxSize 16KB (gzip)

PASS  ./dist/bundles/elastic-apm-opentracing.umd.min.js: 17.08KB < maxSize 18KB (gzip)
PASS  ./dist/rollup/elastic-apm-opentracing.umd.min.js: 16.63KB < maxSize 18KB (gzip)
```

**Comment by vigneshshanmugam** [comment]
Closing the issue since the wins switching to rollup was not huge.
