### ISSUE TITLE
[meta][docs] Align RUM Agent documentation

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-agent-rum-js#511]
A meta issue for tracking RUM documentation changes outlined in https://github.com/elastic/apm-dev/issues/425.

### Doc restructure
- [x] `master` - https://github.com/elastic/apm-agent-rum-js/pull/512
- [x] `4.x` changes ready for the next release.

### Build release notes to docs: 
More details: https://github.com/elastic/apm/issues/132.
The PRs in each group must be merged at the same time to prevent breaking the doc build.

#### `master`
- [x] `elastic/apm-agent-rum-js` - https://github.com/elastic/apm-agent-rum-js/pull/516
- [x] `elastic/docs` - https://github.com/elastic/docs/pull/1518

#### `4.x`
- [x] `elastic/apm-agent-rum-js` - https://github.com/elastic/apm-agent-rum-js/pull/523
- [x] `elastic/docs` - https://github.com/elastic/docs/pull/1519
