### ISSUE TITLE
Remove unnecessary config options

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#628]
We should apply these only to managed transactions and remove the config option
- `checkBrowserResponsiveness`
- `groupSimilarSpans`
- `similarSpanThreshold`
- `transactionDurationThreshold` 

We should double check these with backend:
- `errorThrottleLimit`
- `errorThrottleInterval`
- `transactionThrottleLimit`
- `transactionThrottleInterval`
- `debug` -> we already have the `logLevel` so there's no need for this.
- `queueLimit` -> We might need this config if we support offline

**Comment by vigneshshanmugam** [comment]
### Findings

+ **debug** - Can be safely removed as most of the agents except for python, already removed it and this option is not supported for remote config. 

+ `flushInterval` and `queueLimit` are replaced with `apiRequestTime` and `apiRequestSize` in backend agents. We might not need to follow the same since out connection doesnt stay open and our size might differ with backend agents since gzip/no-gzip. Have to come to an agreement on these

**Comment by jahtalab** [comment]
We decided to keep `flushInterval` as it is today since, `apiRequestTime` supports a different format (e.g. with units) and that's not what we want to support at this point. `apiRequestSize` is not relevant for us since we send the transaction and all of it's spans within the same request.

We will keep `queueLimit` for now, but decided to merge the 4 throttling configs to only one config. This config will apply to both transactions and Errors and it will have a fixed interval (e.g. 1 minute), it can be called something like `eventPerMin` (or similar)

**Comment by vigneshshanmugam** [comment]
### Subtasks

+ [ ] Remove Debug option from the code #670 
+ [ ] Single queue for reporting events #664 
+ [ ] Update docs with `eventsPerMin` and remove throttleInterval and throttleLimit.
