### ISSUE TITLE
Add support for Angular 9, 10 and 11

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/apm-agent-rum-js#962]
Angular 8 is deprecated (up to 8.2.2 is supported by the current RUM Agent), in favour of:
* Angular 9 - released Feb 2020, LTS ends Aug 2021
* Angular 10 - released Jun 2020, LTS ends Dec 2021
* Angular 11 - released Nov 2020, LTS ends May 2022

ACs:
* Update the RUM Agent to work with Angular versions 9, 10 and 11

### Sub Tasks
+ [x] Add support for Angular 9
+ [x] Move the build system to `ng` to add support for Angular Package Format and AOT compiler. Issues - elastic/apm-agent-rum-js#757 elastic/apm-agent-rum-js#463 elastic/apm-agent-rum-js#693 elastic/apm-agent-rum-js#884
+ [x] Provide typings for the `elastic/angular` package. As part of the move to `ng`, this would be automatic. 
+ [x] Move the E2E test to the `ng` build system and use the new library once we land support for angular 9. Issues - elastic/apm-agent-rum-js#450 
+ [x] Update docs with the new angular package - #1000 
+ [ ] Release a new major version for Angular 9
